config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'items#index'
  resources :carts, only: [:index]
  devise_for :users
  resources :orders, only: [:index, :new, :create]
  post '/add_item' => 'carts#add_item'
  delete '/delete_item' => 'carts#delete_item'
  resources :cart_items, only: [:index, :create, :destroy]
end

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ApplicationRecord
  has_many :cart_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item, only: [:add_item, :delete_item]
  skip_before_action :authenticate_user!
  
  def index
    @cart_items = current_cart.cart_items
  end

  def add_item
    @cart_item = current_cart.cart_items.build(item_id: params[:item_id].to_i) if @cart_item.blank?
    @cart_item.quantity += params[:quantity].to_i
    @cart_item.save!
    redirect_to root_path, flash: {success: '追加しました！'}
  end

  def delete_item
    @cart_item.destroy
    redirect_to carts_path, flash: {success: '削除しました！'}
  end

  private

  def setup_cart_item
    @cart_item = current_cart.cart_items.find_by(item_id: params[:item_id].to_i)
  end
end

app/views/carts/_cart_item.html.haml
%tr
  %td
    = image_tag cart_item.item.image.url, class: "Card image cap"
    =cart_item.item.name
  %td=number_to_currency(cart_item.item.price, :format => "%u%n", :unit => "￥")
  %td
    =cart_item.quantity
    点
  %td
    = link_to '削除', delete_item_path(item_id: cart_item.item.id), method: :delete, data: { confirm: '本当に削除しますか？' }