config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'items#index'
  resources :carts, only: [:index]
  devise_for :users
  resources :orders, only: [:index, :new, :create]
  post '/add_item' => 'carts#add_item'
  delete '/delete_item' => 'carts#delete_item'
  resources :cart_items, only: [:index, :create, :destroy]
end

app/models/cart_item.rb
# == Schema Information
#
# Table name: cart_items
#
#  id         :integer          not null, primary key
#  quantity   :integer          default(0), not null
#  item_id    :integer
#  cart_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart

  def self.sum_price(cart_items)
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.item.price * cart_item.quantity
    end
    sum
  end

  # ここの書き方はなんかすっきりしない
  def self.get_delivery_cash(cart_items)
    sum = self.sum_price(cart_items)
    case sum
    when 0..9999
      300
    when 10000...29999
      400
    when 30000...99999
      600
    else
      1000
    end
  end

  def self.get_postage(cart_items)
    1 if cart_items.count < 5
    if cart_items.count % 5 == 0
      times = cart_items.count.div(5)
    else
      times = cart_items.count.div(5) + 1
    end
    times * 600
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @cart_items = current_cart.cart_items
  end

  def create
    @cart_item = current_cart.cart_items.find_by(item_id: params[:item_id].to_i)
    @cart_item = current_cart.cart_items.build(item_id: params[:item_id].to_i) if @cart_item.blank?
    @cart_item.quantity += params[:quantity].to_i
    if @cart_item.save
      redirect_to root_path, flash: {success: '追加しました！'}
    else
      redirect_to root_path, flash: {success: '失敗しました。'}
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to cart_items_path, flash: {success: '削除しました！'}
  end
end

app/views/cart_items/_cart_item.html.haml
%tr
  %td
    = image_tag cart_item.item.image.url, class: "Card image cap"
    =cart_item.item.name
  %td=number_to_currency(cart_item.item.price, :format => "%u%n", :unit => "￥")
  %td
    =cart_item.quantity
    点
  %td
    = link_to '削除', cart_item, method: :delete, data: { confirm: '本当に削除しますか？' }

app/views/cart_items/index.html.haml
.container
  .row
    .col-md-9.mt-2
      %h4.mb-3 ショピングカート
      - if @cart_items.size != 0
        %table.table
          %thead
            %tr
              %th 商品名
              %th 価格
              %th 数量
              %th
          %tbody
            = render :partial => "cart_item", :collection => @cart_items
            %tr
              %td{:colspan => "4", :align => "right"}
                小計(#{@cart_items.sum(:quantity)}点) #{number_to_currency(CartItem.sum_price(@cart_items), :format => "%u%n", :unit => "￥")}
      - else
        カートには何も入っていません。
    .col-md-3.mt-2
      - if @cart_items.size != 0
        .card.border-secondary.mb-3
          .card-header
            %h5 小計(#{@cart_items.sum(:quantity)}点):#{number_to_currency(CartItem.sum_price(@cart_items), :format => "%u%n", :unit => "￥")}
          .card-body.text-secondary
            =link_to 'レジに進む', new_order_path, { :class => 'btn btn-primary btn-lg btn-block' }