config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'items#index'
  resources :carts, only: [:index]
  devise_for :users
  resources :orders, only: [:index, :new, :create]
  post '/add_item' => 'carts#add_item'
  delete '/delete_item' => 'carts#delete_item'
  resources :cart_items, only: [:index, :create, :destroy]
end

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  - key = "info" if key == "notice"
  - key = "danger"  if key == "alert"
  = content_tag :div, value, class: "alert alert-#{key}"

app/views/layouts/_footer.html.haml
%footer.my-5.pt-5.text-muted.text-center.text-small
  %p.mb-1 © 2017-2018 Sakura Market

app/views/layouts/_header.html.haml
.d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.text-white.bg-success.border-bottom.box-shadow
  %h5.my-0.mr-md-auto.font-weight-normal
    = link_to 'さくらマーケット', root_path, class: 'text-white'
  %nav.my-2.my-md-0.mr-md-3
    - if user_signed_in?
      = link_to 'マイページ', edit_user_registration_path, class: 'p-2 text-white'
      = link_to '注文履歴', orders_path, class: 'p-2 text-white'
      = link_to 'ショッピングカート', cart_items_path, class: 'p-2 text-white'
      = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'p-2 text-white'
    - else
      = link_to 'お買い物', '#', class: 'p-2 text-white'
      = link_to 'ショッピングカート', cart_items_path, class: 'p-2 text-white'
      = link_to 'ログイン', user_session_path, class: 'p-2 text-white'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
    = csrf_meta_tags

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %body
      = render 'layouts/header'
      = render 'layouts/flash'
      = yield
      = render 'layouts/footer'
  　　　